version: '3.2'

services:
  postgres:
    image: 'postgres:9.6'
    environment:
      - POSTGRES_USER=cbdb
      - POSTGRES_PASSWORD=cbdb
      - POSTGRES_DB=cbdb
  cronapi:
    build: .
    depends_on:
      - postgres
    image: 'codingblocks/cbdb'
    ports:
      - "8080:80"
    env_file:
      - '.env'