# Generated by Django 3.1.7 on 2021-02-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('heading1', models.CharField(max_length=200)),
                ('heading2', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=200)),
                ('subText', models.CharField(max_length=200)),
                ('img_url', models.URLField()),
                ('cta', models.CharField(max_length=200)),
                ('bg_color', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MiniBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('img_url', models.URLField()),
            ],
        ),
    ]
