# Generated by Django 3.1.7 on 2021-02-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subTitle', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=500)),
                ('img', models.URLField()),
                ('company_logo', models.URLField()),
                ('company_name', models.URLField()),
                ('college', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
            ],
        ),
    ]
