# Generated by Django 3.1.7 on 2021-03-04 17:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_successstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('mrp', models.IntegerField()),
                ('theme', models.CharField(choices=[('1', 'blue'), ('2', 'green'), ('3', 'orange'), ('4', 'pink'), ('5', 'purple')], default='1', max_length=200)),
                ('logo', models.URLField()),
                ('title', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
                ('number_ratings', models.IntegerField()),
                ('slug', models.CharField(max_length=1000)),
                ('start_day', models.DateField()),
                ('registrations_open_day', models.DateField()),
                ('video_link', models.URLField()),
                ('description', models.CharField(max_length=10000)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=2)),
                ('duration', models.CharField(max_length=200)),
                ('buy_link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='successstory',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
    ]
