# Generated by Django 3.1.7 on 2021-03-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210304_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phoneNo', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='theme',
            field=models.CharField(choices=[('theme-blue', 'blue'), ('theme-green', 'green'), ('theme-orange', 'orange'), ('theme-pink', 'pink'), ('theme-purple', 'purple')], default='theme-blue', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
