# Generated by Django 3.1.7 on 2021-03-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210305_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='Mrp',
            new_name='mrp',
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=200),
        ),
    ]
