# Generated by Django 3.1.7 on 2021-03-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210317_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='successstory',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='successstory',
            name='lpa',
            field=models.IntegerField(default=0),
        ),
    ]
