# Generated by Django 3.1.7 on 2021-03-18 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210317_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='projects',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='successstory',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='success_stories', to='api.company'),
        ),
    ]
