# Generated by Django 3.1.7 on 2021-03-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210318_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='highlights',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='syallabus',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
