# Generated by Django 3.1.7 on 2021-03-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210318_1022'),
        ('api', '0011_auto_20210318_1017'),
    ]

    operations = [
    ]
