# Generated by Django 3.1.7 on 2021-04-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210402_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstory',
            name='subTitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
