# Generated by Django 3.1.7 on 2021-04-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210409_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration',
            field=models.ManyToManyField(blank=True, null=True, to='api.User'),
        ),
    ]
