# Generated by Django 3.1.7 on 2021-04-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210413_0740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='EventRegistration',
        ),
    ]
