# Generated by Django 3.1.7 on 2021-04-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210413_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='minibanner',
            name='cta',
            field=models.CharField(default='online.codingblocks.com', max_length=200),
            preserve_default=False,
        ),
    ]
