# Generated by Django 3.1.7 on 2021-04-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_minibanner_cta'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faqs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='highlights',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
